env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "en5Cm1w+/4N0I2fGBxuU5NvjwLmNF+O3x3+RjFNd2xkj6peUchWn4moXdL8VJN8/"
language: scala
sudo: false
cache:
  directories:
  - $HOME/.m2
scala:
  - 2.11.11
jdk:
  - oraclejdk8
script:
  - mvn scalastyle:check
  - mvn clean test 
after_success:
  - mvn jacoco:report coveralls:report
